/* eslint-disable prettier/prettier */
export interface InterfaceApi {
  count: number;
  next: string;
  previus: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
  species?: string;
}

export interface SimpleList {
  id: string;
  name: string;
  picture: string;
  species?: string;
}

// Generated by https://quicktype.io

export interface PersonajeDatos {
  id: number;
  name: string;
  status: string;
  species: string;
  type: string;
  gender: string;
  origin: Location;
  location: Location;
  image: string;
  episode: string[];
  url: string;
  created: string;
}

export interface Location {
  name: string;
  url: string;
}
